# Generated by Django 3.0 on 2023-07-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_experience', models.FloatField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
